# Generated by Django 3.1.14 on 2022-12-29 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_massage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMassage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.CharField(max_length=200)),
                ('your_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('massage', models.TextField(blank=True)),
            ],
        ),
    ]
